import '@src/common.blocks/common.sass'
import '@src/fonts/quicksand-regular/fonts.css'
import '@src/fonts/quicksand-bold/fonts.css'
import '@src/fonts/montserrat-regular/fonts.css'
import '@src/fonts/montserrat-bold/fonts.css'
import '@src/library.blocks/dropdown/dropdown.js'
import '@src/library.blocks/dropdown/__button/dropdown__button.js'
import '@src/library.blocks/dropdown/__increase-button/dropdown__increase-button.js'
import '@src/library.blocks/dropdown/__decrease-button/dropdown__decrease-button.js'
import '@/node_modules/normalize.css'

